.ci/azure-pipelines.yml
.ci/macos-install-python.sh

This PR implements Python 3.8 unit testing for `pyvistaqt` on Windows and Mac OS, both utilizing VTK 9.  Linux isn't there yet.
Also implements wheel building for Windows.

Python 3.8 Unit Testing

---

pyvistaqt/plotting.py

ENH: Add pinch-to-zoom

---

docs/api_reference.rst
pyvistaqt/plotting.py

Working on #20 in #21 I started documenting the inheritance and realized that it could probably be simplified by killing `QVTKRenderWindowInteractorAdapter` altogether. This code:
```
import pyvista as pv
from pyvistaqt import BackgroundPlotter as Plotter
from pyvistaqt.plotting import logger
logger.setLevel(10)  # debug
p = Plotter()
p.show()
```
Outputs:
```
BackgroundPlotter init start
QtInteractor init start
BasePlotter init start
BasePlotter init stop
QtInteractor init stop
BackgroundPlotter init stop
```
Which looks like the correct init order to me.
It also:
1. explicitly parents each Qt widget created to what I think should be the correct parent.
2. documents the inheritance and construction order
3. Adds a `self.interactor = self` alias so that code (like MNE) that uses …

MAINT: Simpler inheritance

---

.ci/azure-pipelines.yml

Fixes codecov report by uploading the coverage report after testing the core api.  Otherwise, the coverage gets overwritten with the docstring testing and that's uploaded instead (showing no coverage).

Upload coverage after core coverage

---

Makefile

This small PR brings some conveniance targets to the `Makefile`.
It's just so much easier to type `make coverage` instead of remembering the full command everytime.

Add Makefile targets for coverage

---

.github/workflows/pythonpackage.yml
Makefile
README.rst
pyvistaqt/_version.py
pyvistaqt/plotting.py

:new: black CI by GitHub Actions for issue #30
In this PR. We need to run GitHub Actions.

:new: black CI by GitHub Actions #30

---

pyvistaqt/editor.py
pyvistaqt/plotting.py
tests/test_plotting.py

This PR follows @banesullivan's idea in https://github.com/pyvista/pyvista-support/issues/182#issuecomment-645496798 and adds a (very) basic editor of the scene actor properties.
This is still a work in progress:
*I use a tiling window manager :sweat_smile:*
<details>
<summary>Code snippet</summary>
```py
import pyvista as pv
from pyvistaqt import BackgroundPlotter as Plotter
p = Plotter()
p.add_mesh(pv.Cone())
p.add_mesh(pv.Sphere(), name='Sphere')
p.add_mesh(pv.Cylinder(), name='Cylinder')
```
</details>
Also relevant to https://github.com/pyvista/pyvistaqt/issues/10

Add basic Editor

---

pyvistaqt/plotting.py
requirements_test.txt
tests/test_plotting.py

💚 Add Ipython test and check it in CI

---

pyvistaqt/plotting.py
tests/test_plotting.py

This is an attempt to fix https://github.com/pyvista/pyvistaqt/issues/62
So far I override `enable()` and `disable()` in `BackgroundPlotter` with a naive:
```py
def enable(self):
self.renderer.enable()
def disable(self):
self.renderer.enable()
```
But this does not work :cry:

Override enable/disable

---

docs/conf.py
environment.yml
pyvistaqt/plotting.py
tests/test_plotting.py

Let's see how to make continuous integration smoother.
Ideas:
* Add a cron-based github action runner on Linux Python3.8

MNT: Check CIs

---

pyvistaqt/_version.py

This PR follows https://github.com/pyvista/pyvistaqt/pull/76#issuecomment-763725015 and bumps the minor version to `0.3.0`

MNT: Bump version

---

.github/workflows/ci.yml

This PR adds a schedule for the GitHub Actions CIs. This will help to relieve the pain of https://github.com/pyvista/pyvistaqt/pull/76 for example. By failing early, it draws attention on maintenance at least. What do you think @pyvista/developers ?

MNT: Add GHA schedule

---

pyvistaqt/plotting.py

Fix the camera position in subplots

---

docs/usage.rst

There is a difference in `usage.rst` between `MyMainWindow` and the `TstWindow` tested in `tests/plotting.py`, mainly the `signal_close` is missing causing the plotter to hang (as explained in https://github.com/pyvista/pyvistaqt/issues/92).

FIX: usage

---

pyvistaqt/_version.py

This PR follows https://github.com/pyvista/pyvistaqt/pull/106 and bumps the version to `0.5.dev0`.

Bump version

---

pyvistaqt/plotting.py
tests/test_plotting.py

Write a little wrapper that allows us to use `global_theme.*` instead of using `rcParams`, but have it wrap to `rcParams` on older PyVista.

MAINT: More updates

---

tests/test_plotting.py

`waitForWindowShown` has been deprecated recently, it is now recommended to use `wait_exposed` instead:
```
>       warnings.warn(
"waitForWindowShown is deprecated, as the underlying Qt method was "
"obsoleted in Qt 5.0 and removed in Qt 6.0. Its name is imprecise and "
"the pytest-qt wrapper does not raise TimeoutError if the window "
"wasn't shown. Please use the qtbot.waitExposed context manager "
"instead.",
DeprecationWarning,
)
E       DeprecationWarning: waitForWindowShown is deprecated, as the underlying Qt method was obsoleted in Qt 5.0 and removed in Qt 6.0. Its name is imprecise and the pytest-qt wrapper does not raise TimeoutError if the window wasn't shown. Please use the qtbot.waitExposed context manager instead.
```
Maybe the timeout needs to be adjusted for macOS.

MNT: Use wait_exposed

---

pyvistaqt/editor.py
pyvistaqt/plotting.py

This PR switches vtk imports to either use `pyvista._vtk` or `vtkmodules`.  This results in a reduction in import time, but also permits the user to avoid including the entire `vtk` library when freezing the application with `pyinstaller` or another freezing library.
It's slightly messy because we currently allow `pyvista>=0.29.0`.  Should we raise this to `0.29.0` in the `setup.py`, we can avoid adding this in.

Improve import speed

---

pyvistaqt/plotting.py

Qt callbacks should never raise an error or you get a segfault:
https://github.com/mne-tools/mne-python/pull/9803/checks?check_run_id=3796599057
```
E   subprocess.CalledProcessError: Command '['/opt/hostedtoolcache/Python/3.9.7/x64/bin/python', '-uc', "import mne; mne.viz.create_3d_figure((800, 600)); backend = mne.viz.get_3d_backend(); assert backend == 'pyvistaqt', backend"]' died with <Signals.SIGABRT: 6>.
...
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/pyvistaqt/plotting.py", line 602, in close
self.app_window.close()
RuntimeError: wrapped C/C++ object of type MainWindow has been deleted
```
This PR just more safely wraps the handler in a try/except to avoid this.

FIX: Safer close

---

pyvistaqt/plotting.py
tests/test_plotting.py

Fixes #131 
Allows to link the views of two different Plotters.
* A `link_views_across_plotters` method has been added to `pyvistaqt.plotting.QtInteractor`. It will link a view of the current QtInteractor with specified views of a second QtInteractor.
* I thought creating a new method for this rather than overloading `pyvista.plotting.plotting.BasePlotter` was a little simpler and easier to read, but I'm happy change it if you feel otherwise.
* I havent added an `unlink_views_across_plotters` method as `pyvista.plotting.plotting.BasePlotter.unlink_views` can still be used for this.
* I thought about testing but I'm not too sure how to go about it. Here's the tests for pyvista's `link_views`: https://github.com/pyvista/pyvista/blob/main/tests/plotting/test_plotting.py#L1318-L1338 Would …

Enable linking views across two Plotters

---

.github/dependabot.yml
.github/workflows/ci.yml
tests/test_plotting.py

The `codecov/codecov-action@v1` action will be deprecated as of 1 Feb 2022. This PR upgrades the action to `v2`
> Due to the deprecation of the underlying bash uploader, the Codecov GitHub Action has released v2 which will use the new uploader. You can learn more about our deprecation plan and the new uploader on our blog.
See https://about.codecov.io/blog/introducing-codecovs-new-uploader/ for more details.
---
Maintenance of our GitHub actions can be simplified and partially automated by enabling dependabot for GitHub actions. This has been added in this PR.
---
Looks like `distutils` has been deprecated:
```
>       if LooseVersion(pyvista.__version__) < '0.27.0':
tests/test_plotting.py:722: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = …
```

update codecov action and add dependabot

---

pyvistaqt/plotting.py
tests/test_plotting.py

This is just a proof-of-concept @GuillaumeFavelier and I cooked up earlier today to make for a smoother pinch-zooming experience on macOS while keeping CPU utilization low.
We're refreshing at a higher frequency during the pinch action, and reset the update interval to the previous value as soon as the pinch action has ended.
We monitored CPU usage and indeed it returns to ~0 after the pinching is over.
cc @agramfort @larsoner, this makes for a **much** nicer experience with MNE `plot_alignment()` on the Mac.

Continuously update zoom level during pinch action

---

Makefile
mypy_checklist.txt

This PR adds a checklist file to `mypy` to go around the issue we encounter with `exclude` in https://github.com/pyvista/pyvistaqt/pull/149.
Related to https://github.com/python/mypy/issues/11760

MNT: mypy checklist

---

pyvistaqt/plotting.py
tests/test_plotting.py

Over in MNE-Python we want to subclass the MainWindow that is instantiated by BackgroundPlotter to override event processing (https://github.com/mne-tools/mne-python/issues/9182#issuecomment-805737809) .This PR makes it possible to pass the class to use for instantiation.

ENH: Allow subclassing MainWindow

---

pyvistaqt/rwi.py
tests/test_plotting.py

This PR fixes the issue with the position of the event on Qt6.
This also reveals one of the weaknesses of our testing since we do not simulate clicks. I could take the time to address this in here if I can.
Related to https://github.com/pyvista/pyvistaqt/issues/20#issuecomment-1064069790

FIX: AttributeError MouseMoveEvent on Qt6

---

.github/workflows/ci.yml
.github/workflows/pythonpackage.yml
environment.yml
mypy.ini
pyvistaqt/editor.py
pyvistaqt/plotting.py
requirements_test.txt
setup.py
tests/test_plotting.py

This PR bumps the required version of `pyvista` to `0.32` and effectively removes obsolete or untested code.

MNT: bump pyvista version requirement

---

.github/workflows/ci.yml
mypy_checklist.txt
pyvistaqt/__init__.py
pyvistaqt/plotting.py
tests/conftest.py
tests/test_qt.py

`pyqt` **should not** be in the recipe of `conda-forge/pyvistaqt-feedstock` since `pyvistaqt` does not install *any* Qt API.
The goal of the PR is to help with this issue:
https://github.com/conda-forge/pyvistaqt-feedstock/pull/9#issuecomment-996413063

MNT: conda forge

---

.ci/azure-pipelines.yml
.codespellrc
.flake8
.isort.cfg
.pre-commit-config.yaml
.pycodestyle
.pylintrc
Makefile
environment.yml
ignore_words.txt
mypy.ini
pyproject.toml
requirements_docs.txt
requirements_test.txt
setup.py

The purpose of this PR is a series of formatting changes to bring `pyvistaqt` formatting tools up to date:
+ Add  `black` and `pydocstyle` configuration options to `pyproject.toml` (matching options in `Makefile` and those in `pyvista` repo and adding corresponding support in `.isort.cfg`)
+ [x] Fix known issues using `mypy`, `isort`, `black`, and `pydocstyle` with `pre-commit` (a07f259)

Update Formatting Tools

---

.ci/setup_headless_display.sh
environment.yml
pyvistaqt/plotting.py
pyvistaqt/rwi.py
requirements_test.txt
tests/test_plotting.py

Hopefully will show a failure with latest pyvista observed in MNE-Python

MAINT: Add scraper test

---

pyvistaqt/_version.py

It has been almost a year since our last release. This is just a bugfix release so I think 0.9.1 is appropriate, but we could do 0.10.0 instead if people want.

MAINT: Set version for patch release

---

.github/workflows/ci.yml
pyvistaqt/plotting.py

Should fix the failure in #354

MAINT: Use main of setup-headless-display-action

---

.gitignore
.pylintrc
mypy_checklist.txt
pyvistaqt/__init__.py
pyvistaqt/_version.py
setup.py

In many repos I work with we've moved to `setuptools_scm` for version control. It's great because when you cut a release on GitHub with a tag like 0.10.0, that will automatically show up as the version in PyPI and sdist, but the next PR that gets merged will show up as `0.11.0.dev<bunch of info>`. It thus adds info and gets rid of the need to manually tick versions -- you can just cut a release on GitHub and be done.
The only downside I've noticed is that downstream packages need to do `git+https://github.com/pyvista/pyvistaqt` to install latest `main` rather than using a `zipball`, but this is a minor drawback and easily worked around I think.

MAINT: Use setuptools_scm for versioning

---

setup.py

`importlib_resources` isn't actually needed for `setuptools_scm` functionality so remove it.

BUG: Fix bug with requirements

---

pyproject.toml
pyvistaqt/editor.py
pyvistaqt/plotting.py
tests/test_plotting.py

Companion PR to https://github.com/pyvista/pyvista/pull/4486

MAINT: Update imports

---

.github/workflows/release.yml

MAINT: Release automatically

---

.pre-commit-config.yaml
docs/conf.py

This is a hack but let's see if it works first
@banesullivan I looked a bit but couldn't find the right way to transition from rcParams to something new, any hints? Maybe it should show up with a `git grep rcParams` in `pyvista`?

MAINT: Fix for latest pyvista

---

.github/dependabot.yml

I have been a bit unhappy at the frequency of dependabot emails, reviews, and merges that we've had to do. I think restricting `pip` to once per month is much more appropriate given the activity level of this repo. Restricting the actions to weekly seems good enough since they're rarely updated.

MAINT: Reduce dependabot frequency

---

.pre-commit-config.yaml

Following https://github.com/pyvista/pyvista/pull/5538.

Bump flake8-isort to 6.1.1

---

pyvistaqt/rwi.py

Will upstream this fix as well

BUG: Fix bug with PyQt6 HiDPI

---

.github/release.yml
pyvistaqt/plotting.py

So this is a problem:
```
$ python -c "from IPython.external.qt_for_kernel import QtGui; print(QtGui)"
<module 'PySide6.QtPrintSupport' from '/home/larsoner/python/virtualenvs/base/lib/python3.12/site-packages/PySide6/QtPrintSupport.abi3.so'>
```
The source file for `qt_for_external` says that it's kept for backward compat, so perhaps no surprise it doesn't work. I don't see any reason we need to triage based on being in ipython or not, though, given everything else comes from `qtpy` earlier anyway.
@tkoyama010 you added this in https://github.com/pyvista/pyvistaqt/pull/40/files#diff-bcab1285ff8ba2b1a25b18d87cd02a09eca4194b83196ba0c2b7939c76393d01R65, any recollection why it was necessary?

BUG: Fix PySide6 compatibility

---

.github/workflows/ci.yml
tests/test_plotting.py

ref https://github.com/pyvista/pyvistaqt/pull/662#issuecomment-2512217877

Switch conda CIs from PyQt5 to PySide6

---

pyvistaqt/editor.py

The `BackgroundPlotter` accesses a private variable of 3rd party imported class, i.e. `Renderer._actors`. But there is no need to access a private property here since `Renderer.actors` simply returns `Renderer._actors` already anyway.
See `Renderer.actors` source:
https://github.com/pyvista/pyvista/blob/5be64528b73a970df364b4e2dd7ebfa0b62e9b64/pyvista/plotting/renderer.py#L818-L821
The underlying implementation for  `Renderer._actors` is being modified by https://github.com/pyvista/pyvista/pull/7184 and the access to a private variable here by `pyvistaqt` is causing integration tests to fail unexpectedly.
EDIT: This was addressed upstream by implementing an `_actors.items()`  method, so this change is not strictly needed by https://github.com/pyvista/pyvista/pull/7184, but I still think …

Do not access private `Renderer._actors` property

---

.github/workflows/update-pr-branch.yml

Potential fix for [https://github.com/pyvista/pyvistaqt/security/code-scanning/3](https://github.com/pyvista/pyvistaqt/security/code-scanning/3)
To fix the issue, add a `permissions` block to the workflow. Since the workflow interacts with pull requests, it requires `pull-requests: write` permission. Additionally, to ensure minimal permissions, set `contents: read` to allow basic repository access. These permissions should be added at the job level to scope them specifically to the `autoupdate` job.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 3: Workflow does not contain permissions

---

.github/workflows/docbuild.yml

Potential fix for [https://github.com/pyvista/pyvistaqt/security/code-scanning/1](https://github.com/pyvista/pyvistaqt/security/code-scanning/1)
To fix the issue, we will add a `permissions` block at the root of the workflow file. This block will specify the minimal permissions required for the workflow to function correctly. Based on the workflow's steps, the following permissions are needed:
- `contents: read` for accessing the repository's contents.
- `pages: write` for deploying the documentation to GitHub Pages.
The `permissions` block will be added at the top level of the workflow, ensuring it applies to all jobs unless overridden by a job-specific `permissions` block.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 1: Workflow does not contain permissions

---

.github/workflows/update-pr-branch.yml

Potential fix for [https://github.com/pyvista/pyvistaqt/security/code-scanning/6](https://github.com/pyvista/pyvistaqt/security/code-scanning/6)
To fix the issue, we will add a `permissions` block at the root of the workflow file. This block will explicitly define the minimal permissions required for the workflow to function. Based on the workflow's purpose (updating pull requests), the `pull-requests: write` permission is necessary. Additionally, the `contents: read` permission is required for accessing repository contents, which is a common minimal permission.
The `permissions` block will be added after the `name` field and before the `on` field to apply these permissions to all jobs in the workflow.
---
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Potential fix for code scanning alert no. 6: Workflow does not contain permissions

---

docs/_templates/layout.html
pyvistaqt/editor.py

Upstream as part of https://github.com/pyvista/pyvista/pull/7716, setting dynamic attributes on the plotter will no longer be allowed. As such, `BasePlotter.axes_widget` is set to `None` during init. This means that it's no longer sufficient to check if the attribute exists, and it's necessary to also check it's not None.
I am seeing integration test failures here:
https://github.com/pyvista/pyvista/actions/runs/16335129476/job/46145621302?pr=7716#step:8:1177
I'm pretty sure they'll all be resolved by this PR

Check that `axes_widget` is truthy

---

.github/release.yml

I want to cut a release to be compatible with PyVista when it comes out, but noticed the notes had a bunch of bot names in them. So I'll merge this then cut a 0.11.3

MAINT: Remove bots from release notes
