README.rst
docs/index.rst
docs/qt_plotting.rst

Fix some leftovers from the renaming

pyvista-qt -> pyvistaqt

---

.ci/azure-pipelines.yml

Deploy sdist to PyPI

---

.ci/azure-pipelines.yml
.gitignore
README.rst
codecov.yml

This PR adds basic code coverage reporting.
Resolves #29

Add basic codecov

---

codecov.yml

For some reason coverage remains `0%` on master.

Check coverage

---

pyvistaqt/plotting.py
tests/test_plotting.py

This PR improves the coverage. I'll see how far I can go.

Improve coverage

---

.github/workflows/pythonpackage.yml
.isort.cfg
Makefile
README.rst
docs/conf.py
pyvistaqt/__init__.py
pyvistaqt/plotting.py
setup.py
tests/test_plotting.py

Let's add [isort](https://github.com/timothycrosley/isort) in CI !

💚 Add isort in CI

---

.ci/azure-pipelines.yml
setup.py

🌇 Python3.5 security support Ended 1 week and 3 days ago (13 Sep 2020). Let's finish support for it.
- https://endoflife.date/python
- See https://github.com/pyvista/pyvistaqt/pull/47
- See https://github.com/pyvista/pyvista/pull/905

🌇 Sunset of Python3.5

---

docs/usage.rst

This PR adds a warning cell in the doc. It hopefully helps clear out some misunderstanding.
Closes https://github.com/pyvista/pyvistaqt/issues/74

Update doc with event loop explanation

---

docs/usage.rst
pyvistaqt/plotting.py
tests/test_plotting.py

This PR updates `update_app_icon` and adds a way to disable app icon completely.

Allow update_app_icon parameter to be None

---

.ci/azure-pipelines.yml
pyvistaqt/plotting.py
tests/conftest.py
tests/test_plotting.py

This PR is a small subset of #66. Hopefully, it is easily mergeable and it can help solving the conflicts in #66 itself.

MNT: Prepare for GC test

---

.github/workflows/ci.yml
pyvistaqt/plotting.py
pyvistaqt/utils.py
tests/test_plotting.py

This PR adds a job that tests against PyVista master instead of the latest released version.
Closes https://github.com/pyvista/pyvistaqt/issues/94
Related to https://github.com/pyvista/pyvista/pull/1257

MNT: Add PIP pre job

---

pyvistaqt/_version.py

This PR follows https://github.com/pyvista/pyvista/pull/965 and similarly updates the version.
Related to https://github.com/mne-tools/mne-python/pull/9291#issuecomment-821186527

FIX: version

---

pyvistaqt/_version.py

This PR follows https://github.com/pyvista/pyvista/pull/1257 and prepares the release of `pyvistaqt 0.4.0`.

Release 0.4.0

---

pyvistaqt/plotting.py

https://github.com/pyvista/pyvista/pull/1310 broke things in pyvistaqt:
https://app.circleci.com/pipelines/github/mne-tools/mne-python/8243/workflows/ab89194f-358e-4ed6-9cd1-3e9ca7fdebfa/jobs/28518
This should fix it by importing `rcParams` from `pyvista` root directly

FIX: Import from root

---

pyvistaqt/plotting.py

Last merge was accidental, but this hopefully satisfies style

FIX: isort conflict

---

.github/workflows/ci.yml
pytest.ini
pyvistaqt/dialog.py
pyvistaqt/plotting.py

This PR follows https://github.com/pyvista/pyvistaqt/pull/109#issuecomment-843143140 and updates GitHub Actions matrix with `pyvista`.

MNT: Test against different pyvista versions

---

README.rst
pyvistaqt/counter.py
pyvistaqt/dialog.py

This PR adds a badge for GitHub Actions, `mypy` and `pylint`. It also approves consistency in styling and solves a few `R1725`s:
```
Consider using Python 3 style super() without arguments (super-with-arguments)
```

MNT: Badge

---

.ci/azure-pipelines.yml
.ci/setup_headless_display.sh
.github/workflows/ci.yml
requirements_docs.txt
tests/test_plotting.py

This PR:
- Upgrades Ubuntu on Azure
- Use one script to configure xvfb
- Adds a `pip-pre` job (ubuntu-latest, py3.9, vtk9, pyvista/master, qtpy/master)
- Adjusts the timeout for a MacOS test
- Adds `matplotlib` dependency in `requirements_doc.txt`
It's still work in progress, I don't think the CIs will come back happy after only one commit.

MNT: Upgrade ubuntu and add pip-pre

---

.github/workflows/ci.yml

This PR follows https://github.com/pyvista/pyvista/issues/1389 and updates internal refs.

Rename master to main

---

.github/workflows/pythonpackage.yml
pyvistaqt/dialog.py
pyvistaqt/editor.py
pyvistaqt/plotting.py

The CI branch is still master, so CI was not working. I set the branch to "*" to solve the problem.

Fix CI branch master -> '*'

---

CONTRIBUTING.md

Ref https://github.com/pyvista/pyvista/pull/2110

Fix CONTRIBUTING.md to CONTRIBUTING.rst

---

README.rst
codecov.yml
docs/conf.py

This PR mainly updates some elements that were still using `master` as branch name.

MNT: Readme

---

.github/workflows/pre-commit-update.yml

Add pre-commit-update

---

.ci/azure-pipelines.yml
.ci/setup_headless_display.sh

Let's make sure CIs are green for https://github.com/pyvista/pyvistaqt/pull/200

MAINT: Update deps for Qt

---

.github/workflows/ci.yml

Add pyvista version 3.8 to CI matrix.

Add pyvista version 3.8 to CI matrix

---

pyvistaqt/_version.py
setup.py

Bumping back to `0.10.dev0`, and fixing a warning I got with `twine check dist/*` before upload

MAINT: Bump back to dev

---

.github/workflows/ci.yml

This should work, might as well use it!

MAINT: Use setup-headless-display-action

---

pyvistaqt/plotting.py
tests/test_plotting.py

Update the VTK.js export functionality to catch up with https://github.com/pyvista/pyvista/pull/4569

Update VTKjs export

---

requirements_test.txt

Update `requirements_test.txt` to remove unused package.

Update `requirements_test.txt` to remove unused package

---

.ci/azure-pipelines.yml
.github/workflows/ci.yml
.github/workflows/docbuild.yml
.github/workflows/release.yml
.pre-commit-config.yaml
CONTRIBUTING.md
codecov.yml
docs/_static/copybutton.css
docs/_static/style.css
docs/_templates/layout.html

Following https://github.com/pyvista/pyvista/pull/5503.

Add prettier check to format non-python code

---

.github/dependabot.yml

Following https://github.com/pyvista/pyvista/pull/5351 to resolve the error of #532.

Add group update settings to `dependabot`

---

.github/workflows/ci.yml

Revert "Build(deps): Bump codecov/codecov-action from 4 to 5 in /.github/workflows"

---

requirements_test.txt

Remove `check-jsonschema` from requirements_test.txt as it is unused.

Remove check-jsonschema from requirements_test.txt as it is unused

---

.github/workflows/update-pr-branch.yml

Revert "Potential fix for code scanning alert no. 3: Workflow does not contain permissions"
